[package]
name = "ruc"
version = "0.6.8"
authors = ["FindoraNetwork"]
edition = "2018"
description = "Rust Util Collection, include a friendly `error-chain` and many other utils."
keywords = ["error", "error-chain"]
categories = ["development-tools::debugging"]
license = "MIT"
homepage = "https://github.com/FindoraNetwork/ruc"
repository = "https://github.com/FindoraNetwork/ruc.git"

[dependencies]
lazy_static = "1.4.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nix = { version = "0.22.1", optional = true }
rand = { version = "0.8.0", optional = true }
time = "0.2.23"

[features]
default = ["ansi"]
ansi = []

rich = ["uau", "cmd"]
uau = ["nix", "rand"]
cmd = []
